name: Deploy Frontend on Azure

on:
  workflow_dispatch:
   inputs:
     environment:
       description: 'Environment to deploy to (dev, staging, prod)'
       required: true
       type: environment
          
jobs:
  Deploy-Frontend:
    environment:
      name: ${{ github.event.inputs.environment }}
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Download Frontend Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-frontend.yml
          name: organizer-frontend
          branch: ${{ steps.extract_branch.outputs.branch }}
          path: ./deploy

    
      - name: Config Settingsâ€¯Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'deploy/assets/config/config.production.json'
        env:
          api.key: ${{ secrets.APPSERVICE_CONFIG_APIKEY }}
          api.url: ${{ vars.APPSERVICE_FE_CONFIG_APIURL }}

      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name:    ${{ vars.APPSERVICENAME_FE }}
          package: ./deploy
        
